server:
  port: 8080
  servlet:
    context-path: /wave

spring:
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:uploads/
  application:
    name: wave
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      auto-commit: true
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 3
      pool-name: HikariPool-wave
    password: ghktkskagyqls123
    url: jdbc:oracle:thin:@3.39.242.126:1522:XE
    username: wave
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      max-file-size: 10MB

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

jwt:
  issuer: hanto0916.gmail.com
  secret: E912C15AA2495217ECD6BE5BEA8D1102

file:
  upload:
    path: uploads


